name: grpc-gateway
route_id: true
protocols:
  - name: http
  - name: https
dbless_compatible: 'yes'
config:
  - name: proto
    required: false
    default: null
    value_in_examples: path/to/hello.proto
    datatype: string
    description: |
      Describes the gRPC types and methods.
      [HTTP configuration](https://github.com/googleapis/googleapis/blob/fc37c47e70b83c1cc5cc1616c9a307c4303fe789/google/api/http.proto)
      must be defined in the file.
