name: route-by-header
service_id: true
route_id: true
consumer_id: true
dbless_compatible: 'yes'
konnect_examples: false
manager_examples: false
config:
  - name: rules
    required: false
    default: {}
    value_in_examples: null
    description: |
      List of [rules](#rules)
